### ISSUE TITLE
deploying is failing "missing public directory"

### ISSUE THREAD

**Issue by orzklv** [waptik/telegram-bot-boilerplate-now-serverless-api#1]

**Comment by waptik** [comment]
Hi, can you include a log output for me to see?

Update: So reployed it on another project(https://telegram-bot-boilerplate-now-serverless-api2.vercel.app/). This is what you need to do:
if you have already deployed the project, go to the settings page of the project and set the output directory to `dist` as seen in [tsconfig.js#L4](https://github.com/waptik/telegram-bot-boilerplate-now-serverless-api/blob/master/tsconfig.json#L4) . See the screenshot https://share.getcloudapp.com/wbuKyqeO

I'll update the readme

**Comment by orzklv** [comment]
aha, thanks for guiding.

**Comment by waptik** [comment]
> aha, thanks for guiding.

You're welcome. Thanks to you, i improved the code as well as the readme. It's now easier to deploy or run locally.

Have a great day!
