### ISSUE TITLE
Telegraf upgrade

### ISSUE THREAD

**Issue by suphero** [waptik/telegram-bot-boilerplate-now-serverless-api#3]
Hi @waptik ,

Thanks for the great boilerplate. Do you have any plan to update this repo to telegraf v4? It is released about 3 weeks ago. https://github.com/telegraf/telegraf/releases/tag/v4.0.0

**Comment by waptik** [comment]
Hi @suphero,

You're welcome! Ummm, not really because the current setup works for me! But you are free to do so!
Just fork the repo, upgrade and test if everything works fine then push it.
I'll merge it if all is ok!

I'm pretty sure others will like it!
